seed: 42
batch_size: 4
optimizer: Adam
optimizer_args:
    lr: 0.0001
    amsgrad: True
epochs: 100
outputpath: experiments_LRS2
model: AV_test_RAVSS
train_scp: lrs2_rebuild/train.txt
val_scp: lrs2_rebuild/dev.txt
test_scp: lrs2_rebuild/test.txt
dataset_root_path: lrs2_rebuild
loss: SI_SNR_PIT
val_loss: SI_SNR
mix_num: 2
target_num: 1
pesq: PESQ
n_saved: 3
num_workers: 4
validate_every: 1
with_amp: True
backend: nccl
nproc_per_node: 1

test_cdp: 
resume_from: 
